controller_list:
  - name: fake_dobot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint12
      - joint23
      - joint34
      - joint45
  - name: fake_dobot_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
#  - group: dobot_arm
#    pose: home

  []