controller_list:
  - name: fake_dobot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  - name: fake_dobot_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_grip
initial:  # Define initial robot poses per group
#  - group: dobot_arm
#    pose: home

  []