dobot:
  # Публикация совместных состояний
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Контроллеры положения
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 60.0, i: 0.0, d: 30.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 10.0, i: 0.0, d: 8.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 60.0, i: 0.0, d: 30.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 10.0, i: 0.0, d: 5.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_grip
    pid: {p: 100.0, i: 0.0, d: 45.0}
